### ISSUE TITLE
Unable to run CouchDB's main.js

### ISSUE THREAD

**Issue by excieve** [dmunch/couch-chakra#2]
I managed to compile both ChakraCore and couch-chakra (although only with the revision of ChakraCore from the Readme, both latest release and latest master fail at various points). However, running CouchDB's JS query server using it crashes:
```
[error] 2017-03-04T18:03:48.878018Z nonode@nohost <0.596.0> -------- OS Process Error <0.27955.0> :: {os_process_error,{exit_status,1}}
```
Apparently there's an error parsing CouchDB's `main.js`:
```
./couch-chakra -d /opt/couchdb/share/server/main.js        


=== ERROR === 
retcode: 0x30002
has exception at 
line 1411
column 10
SyntaxError: Expected '('
list of properties on error object:
message
line
column
length
source
```

This is with CouchDB 2.0.0. And it also happens with "legacy mode" turned on. Am I doing it wrong or it's just that query server is incompatible with Chakra?

**Comment by dmunch** [comment]
Thanks for testing couch-chakra! Good to know it's no longer compiling with current master, going to look into this soon.

Concerning your issue, there's a tiny modification you have to do to the CouchDB 2.0 query server to replace the `for each` statement. See the patch cited below.

```diff
diff --git a/share/server/views.js b/share/server/views.js
index b72c218..2148412 100644
--- a/share/server/views.js
+++ b/share/server/views.js
@@ -109,7 +109,7 @@ var Views = (function() {
       Couch.recursivelySeal(doc);

       var buf = [];
-      for each (fun in State.funs) {
+      State.funs.forEach(function(fun) {
         map_results = [];
         try {
           fun(doc);
@@ -120,7 +120,7 @@ var Views = (function() {
           // did not emit anything, by buffering an empty array.
           buf.push([]);
         }
-      }
+      });
       print(JSON.stringify(buf));
     }
   };
```
In any case I'll be happy about your feedback. 

Just as a side-node, I haven't used couch-chakra in any real-world scenarios yet, but I'm planning to do so in some point soon. So there might be still some edges here and there, and I'll be more than happy to have them reported and fixed. I also have some more changes coming up and I'm currently thinking about a benchmarking strategy, probably based on http://blog.idempotent.ca/2016/12/19/couchdb-indexing-benchmark/  

I'd certainly won't say no to a helping hand on this *hint* *hint* ;)

**Comment by excieve** [comment]
Thanks for this @dmunch! It starts fine now, although I'm getting a number of odd errors with both ES5 and ES6 versions of my map function (which doesn't happen on SpiderMonkey):
```
[error] 2017-03-05T12:31:05.967040Z nonode@nohost <0.1000.0> 9a7d67e6c9 rexi_server throw:{invalid_json,{error,{626,invalid_string}}} [{couch_mrview_util,get_view,4,[{file,"src/couch_mrview_util.erl"},{line,56}]},{couch_mrview,query_view,6,[{file,"src/couch_mrview.erl"},{line,244}]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,139}]}
```
Possibly something in my function doesn't behave well on certain inputs as some end up mapped without errors. Will look into it.

As for benchmarking, I'm actually evaluating various query servers (that's how I found couch-chakra). So far I've tried ES5 with couchjs, CoffeeScript (transpiled), Python on CPython, Python on PyPy, Erlang and jq.

Out of these, obviously Erlang is best in terms of performance but I'm also looking for ease of writing the functions (as this is something analysts will be eventually doing in my project). Couchjs is actually OK but I'd like to have ES6 features without having to transpile. In contrast to the mentioned article PyPy was much better on my dataset (≈300K docs with nested fields totalling 1GB in CouchDB, compressed I think) and function (fairly complex, including iterations over nested fields and calculations) than CPython: 5m against 15m, basically the same as couchjs but I suspect we can do better with possibly better JS runtime.

So far I'm leaning towards providing both JS (with the best runtime) and [jq](https://stedolan.github.io/jq/), which is a nice little DSL for JSON manipulations but the latter needs more work to act as a query server. And, of course, I'm planning to write an article about it when I'm done :)

**Comment by excieve** [comment]
Right, so the problem with `invalid_json` error is an output like this:
```
[debug] 2017-03-05T13:28:43.628652Z nonode@nohost <0.1057.0> -------- OS Process #Port<0.7411> Output :: [[["nacp_febcb39f-b5f4-4f18-8dea-1118fea22e0d",{"FIO":"ДЕМ'ЯНОВСЬКИЙ ОЛЕГ ВАЛЕРІЙОВИЧ","workPost":"начальник відділення соціально-психологічної служби відділу СВПР","workPlace":"Львівська виправна колонія Управління Державної пенітенціарної служби України у Львівській області (№48)","decl_year":"2016","salary_declarant_sum":45343,"salary_family_sum":0,"total_income_declarant":45343,"total_income_family":0}]],[["nacp_febcb39f-b5f4-4f18-8dea-1118fea22e0d",{"FIO":"ДЕМ'ЯНОВСЬКИЙ ОЛЕГ ВАЛЕРІЙОВИЧ","workPost":"начальник відділення соціально-психологічної служби відділ
```
Notice that the output passed back to CouchDB is duplicated and truncated, when the [map function](https://gist.github.com/excieve/22a9f963e82281d23bf6e9139e102819) emits only one dictionary.

Additionally, ES6 without legacy mode seems to segfault now...

**Comment by excieve** [comment]
Nevermind segfault, it was due to mixing ES5 and ES6 views without legacy mode (though probably shouldn't segfault like this). As was duplication — several views of the design doc being processed by the map function.

The issue with ES6 is the same — truncating the output.

**Comment by excieve** [comment]
A very simple map function seems to work for some time and then ends up with this (and somehow my host renders unresponsive):
```
*** Error in `/opt/couch-charka/couch-chakra': double free or corruption (top): 0x0000000001e1d980 ***
*** Error in `/opt/couch-charka/couch-chakra': double free or corruption (!prev): 0x0000000001635020 ***
*** Error in `/opt/couch-charka/couch-chakra': double free or corruption (!prev): 0x00000000021298a0 ***
*** Error in `/opt/couch-charka/couch-chakra': double free or corruption (!prev): 0x0000000001edb650 ***
```

Here's the function:
```.js
(doc) => {
    emit(doc._id, 1)
}
```

**Comment by excieve** [comment]
My wild guess for output truncation is Unicode issues.
`JsGetStringLength` [here](https://github.com/dmunch/couch-chakra/blob/master/src/main.c#L82) apparently returns a number of characters rather than size in bytes, while `malloc` [here](https://github.com/dmunch/couch-chakra/blob/master/src/main.c#L87) expects bytes, thus truncating the resulting string when copying if there are non single-byte characters.

I'm not a C expert though and not sure what's the best way to deal with Unicode issues there.

**Comment by dmunch** [comment]
Pretty good guess I'd say, I just added some Unicode characters to `query_server_spec.rb
` and see the issue popping up right away. I'm about to fix it, stay tuned.

**Comment by dmunch** [comment]
The commit in branch [dmunch-unicode-issues](https://github.com/dmunch/couch-chakra/tree/dmunch-unicode-issues) should fix the printing issue. There might be other unicode issues e.g. in script loading since I think I'm using the same pattern in those places, about to fix them now.

**Comment by dmunch** [comment]
Wrong guess, only one occurrence of `JsGetStringLength` left but it's save since no memory allocation is done with its result.

**Comment by dmunch** [comment]
I created some new issues to handle each case separately. Since we solved the original issue I'm closing this one.

**Comment by excieve** [comment]
Thanks for fixing this @dmunch. It worked flawlessly on my dataset. Performance was comparable to couchjs with SpiderMonkey — both ≈5m on my machine.

**Comment by dmunch** [comment]
Good news! The benchmark I cited suggests that the biggest bottleneck is actually the serializing in the Erlang runtime. I'm about to prepare some modifications to be able to use a binary protocol between the Erlang and the couch-chakra process. I'm not there yet, although not far, but once I finished and the unit tests pass I'd love to see your benchmarks being run against it.

**Comment by dmunch** [comment]
Btw. do you still see https://github.com/dmunch/couch-chakra/issues/3 now that the unicode issue is handled? I would have expected it being another issue, but you seem to say that the issue didn't appear any longer (at least not during ≈5m)

**Comment by excieve** [comment]
No, can't reproduce it anymore. I was seeing it on a simple function, which just emits the doc id and constant. But the same function works well now and by the way it also takes ≈4-5m to process the entire dataset so indeed it seems like the text protocol has some bottlenecks. Very excited about your work on it!
